// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FastBurgerMaker_GameServer
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct time_end_dto : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_8(); }
  public static time_end_dto GetRootAstime_end_dto(ByteBuffer _bb) { return GetRootAstime_end_dto(_bb, new time_end_dto()); }
  public static time_end_dto GetRootAstime_end_dto(ByteBuffer _bb, time_end_dto obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public time_end_dto __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string PlayerSessionId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPlayerSessionIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetPlayerSessionIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetPlayerSessionIdArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<FastBurgerMaker_GameServer.time_end_dto> Createtime_end_dto(FlatBufferBuilder builder,
      StringOffset player_session_idOffset = default(StringOffset)) {
    builder.StartTable(1);
    time_end_dto.AddPlayerSessionId(builder, player_session_idOffset);
    return time_end_dto.Endtime_end_dto(builder);
  }

  public static void Starttime_end_dto(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayerSessionId(FlatBufferBuilder builder, StringOffset playerSessionIdOffset) { builder.AddOffset(0, playerSessionIdOffset.Value, 0); }
  public static Offset<FastBurgerMaker_GameServer.time_end_dto> Endtime_end_dto(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FastBurgerMaker_GameServer.time_end_dto>(o);
  }
}


}
